/**
 * Browser-safe entry point for @curvenote/scms-db
 * 
 * This exports types, enums, and utility types that are safe to use in browser code.
 * It does NOT export the PrismaClient constructor or any Node.js dependencies.
 * 
 * Use this in React components and other client-side code where you need types or enums.
 * 
 * @example
 * ```ts
 * import { UserRole, type User } from '@curvenote/scms-db/browser';
 * 
 * function UserBadge({ role }: { role: UserRole }) {
 *   return role === UserRole.ADMIN ? <span>Admin</span> : <span>User</span>;
 * }
 * ```
 */

// Re-export all browser-safe types, enums, and utilities
// This file is generated by Prisma and contains no server-side code
export * from './generated/browser.js';
