
#let template(
  title: "Untitled",
  short-title: "Generated by Curvenote",
  show-header: true,
  logo: "logo.svg",
  body
) = {
  set document(title: title)
  set page(
    margin: 1in,
    header: if show-header {
      context {
        if counter(page).get().first() >= 1 {
          set text(size: 8pt, fill: gray.darken(40%))
          grid(
            columns: (1fr, auto),
            align: (left, right),
            gutter: 1em,
            short-title,
            image(logo, height: 12pt),
          )
        }
      }
    } else {
      none
    },
  )

  set text(size: 10pt)
  set par(justify: true, spacing: 1em)
  set heading(numbering: "1.1")

  // Title: set text for style, then block gets a single body (title)
  set align(center)
  set text(size: 18pt, weight: "bold")
  block(title)
  v(1em)
  set align(left)
  set text(size: 10pt, weight: "regular")

  // Body (only content after the show rule is passed as body; do not duplicate below)
  body
}