/** A curated slice of Google Fonts for the picker; any family can still be typed by name. */
export const GOOGLE_FONTS: { family: string; category: string }[] = [
  { family: 'Noto Sans', category: 'sans-serif' },
  { family: 'Inter', category: 'sans-serif' },
  { family: 'Roboto', category: 'sans-serif' },
  { family: 'Open Sans', category: 'sans-serif' },
  { family: 'Lato', category: 'sans-serif' },
  { family: 'Montserrat', category: 'sans-serif' },
  { family: 'Source Sans 3', category: 'sans-serif' },
  { family: 'Nunito', category: 'sans-serif' },
  { family: 'Nunito Sans', category: 'sans-serif' },
  { family: 'Poppins', category: 'sans-serif' },
  { family: 'Raleway', category: 'sans-serif' },
  { family: 'Work Sans', category: 'sans-serif' },
  { family: 'Rubik', category: 'sans-serif' },
  { family: 'Manrope', category: 'sans-serif' },
  { family: 'DM Sans', category: 'sans-serif' },
  { family: 'Plus Jakarta Sans', category: 'sans-serif' },
  { family: 'Figtree', category: 'sans-serif' },
  { family: 'Outfit', category: 'sans-serif' },
  { family: 'Karla', category: 'sans-serif' },
  { family: 'Mulish', category: 'sans-serif' },
  { family: 'Barlow', category: 'sans-serif' },
  { family: 'Cabin', category: 'sans-serif' },
  { family: 'Fira Sans', category: 'sans-serif' },
  { family: 'IBM Plex Sans', category: 'sans-serif' },
  { family: 'PT Sans', category: 'sans-serif' },
  { family: 'Ubuntu', category: 'sans-serif' },
  { family: 'Oswald', category: 'sans-serif' },
  { family: 'Archivo', category: 'sans-serif' },
  { family: 'Public Sans', category: 'sans-serif' },
  { family: 'Libre Franklin', category: 'sans-serif' },
  { family: 'Atkinson Hyperlegible', category: 'sans-serif' },
  { family: 'Red Hat Display', category: 'sans-serif' },
  { family: 'Red Hat Text', category: 'sans-serif' },
  { family: 'Josefin Sans', category: 'sans-serif' },
  { family: 'Quicksand', category: 'sans-serif' },
  { family: 'Heebo', category: 'sans-serif' },
  { family: 'Assistant', category: 'sans-serif' },
  { family: 'Hind', category: 'sans-serif' },
  { family: 'Titillium Web', category: 'sans-serif' },
  { family: 'Exo 2', category: 'sans-serif' },
  { family: 'Overpass', category: 'sans-serif' },
  { family: 'Sora', category: 'sans-serif' },
  { family: 'Lexend', category: 'sans-serif' },
  { family: 'Onest', category: 'sans-serif' },
  { family: 'Geist', category: 'sans-serif' },
  { family: 'Instrument Sans', category: 'sans-serif' },
  { family: 'Bricolage Grotesque', category: 'sans-serif' },
  { family: 'Schibsted Grotesk', category: 'sans-serif' },
  { family: 'Albert Sans', category: 'sans-serif' },
  { family: 'Be Vietnam Pro', category: 'sans-serif' },
  { family: 'Chivo', category: 'sans-serif' },
  { family: 'Encode Sans', category: 'sans-serif' },
  { family: 'Jost', category: 'sans-serif' },
  { family: 'Kanit', category: 'sans-serif' },
  { family: 'Mukta', category: 'sans-serif' },
  { family: 'Prompt', category: 'sans-serif' },
  { family: 'Questrial', category: 'sans-serif' },
  { family: 'Signika', category: 'sans-serif' },
  { family: 'Varela Round', category: 'sans-serif' },
  { family: 'Zilla Slab', category: 'sans-serif' },
  { family: 'Noto Serif', category: 'serif' },
  { family: 'Merriweather', category: 'serif' },
  { family: 'Lora', category: 'serif' },
  { family: 'Playfair Display', category: 'serif' },
  { family: 'PT Serif', category: 'serif' },
  { family: 'Source Serif 4', category: 'serif' },
  { family: 'Libre Baskerville', category: 'serif' },
  { family: 'EB Garamond', category: 'serif' },
  { family: 'Crimson Pro', category: 'serif' },
  { family: 'Crimson Text', category: 'serif' },
  { family: 'Cormorant Garamond', category: 'serif' },
  { family: 'Spectral', category: 'serif' },
  { family: 'Literata', category: 'serif' },
  { family: 'Newsreader', category: 'serif' },
  { family: 'Fraunces', category: 'serif' },
  { family: 'DM Serif Display', category: 'serif' },
  { family: 'DM Serif Text', category: 'serif' },
  { family: 'Bitter', category: 'serif' },
  { family: 'Domine', category: 'serif' },
  { family: 'Cardo', category: 'serif' },
  { family: 'Alegreya', category: 'serif' },
  { family: 'Gelasio', category: 'serif' },
  { family: 'Libre Caslon Text', category: 'serif' },
  { family: 'Old Standard TT', category: 'serif' },
  { family: 'Vollkorn', category: 'serif' },
  { family: 'Nanum Myeongjo', category: 'serif' },
  { family: 'Frank Ruhl Libre', category: 'serif' },
  { family: 'Bodoni Moda', category: 'serif' },
  { family: 'Instrument Serif', category: 'serif' },
  { family: 'Young Serif', category: 'serif' },
  { family: 'Noto Serif Display', category: 'serif' },
  { family: 'Roboto Serif', category: 'serif' },
  { family: 'IBM Plex Serif', category: 'serif' },
  { family: 'Arvo', category: 'serif' },
  { family: 'Rokkitt', category: 'serif' },
  { family: 'Roboto Slab', category: 'serif' },
  { family: 'Faustina', category: 'serif' },
  { family: 'Petrona', category: 'serif' },
  { family: 'STIX Two Text', category: 'serif' },
  { family: 'Brygada 1918', category: 'serif' },
  { family: 'Piazzolla', category: 'serif' },
  { family: 'JetBrains Mono', category: 'monospace' },
  { family: 'Fira Code', category: 'monospace' },
  { family: 'Source Code Pro', category: 'monospace' },
  { family: 'IBM Plex Mono', category: 'monospace' },
  { family: 'Roboto Mono', category: 'monospace' },
  { family: 'Ubuntu Mono', category: 'monospace' },
  { family: 'Inconsolata', category: 'monospace' },
  { family: 'Space Mono', category: 'monospace' },
  { family: 'DM Mono', category: 'monospace' },
  { family: 'Noto Sans Mono', category: 'monospace' },
  { family: 'Courier Prime', category: 'monospace' },
  { family: 'Red Hat Mono', category: 'monospace' },
  { family: 'Geist Mono', category: 'monospace' },
  { family: 'Martian Mono', category: 'monospace' },
  { family: 'Azeret Mono', category: 'monospace' },
  { family: 'Overpass Mono', category: 'monospace' },
  { family: 'Cousine', category: 'monospace' },
  { family: 'Anonymous Pro', category: 'monospace' },
  { family: 'Share Tech Mono', category: 'monospace' },
  { family: 'Sometype Mono', category: 'monospace' },
  { family: 'Bebas Neue', category: 'display' },
  { family: 'Anton', category: 'display' },
  { family: 'Righteous', category: 'display' },
  { family: 'Abril Fatface', category: 'display' },
  { family: 'Lobster', category: 'display' },
  { family: 'Pacifico', category: 'display' },
  { family: 'Alfa Slab One', category: 'display' },
  { family: 'Archivo Black', category: 'display' },
  { family: 'Bungee', category: 'display' },
  { family: 'Fredoka', category: 'display' },
  { family: 'Comfortaa', category: 'display' },
  { family: 'Chewy', category: 'display' },
  { family: 'Permanent Marker', category: 'display' },
  { family: 'Special Elite', category: 'display' },
  { family: 'Press Start 2P', category: 'display' },
  { family: 'Silkscreen', category: 'display' },
  { family: 'Unbounded', category: 'display' },
  { family: 'Syne', category: 'display' },
  { family: 'Space Grotesk', category: 'display' },
  { family: 'Familjen Grotesk', category: 'display' },
];
