name: CI

on:
  push:
    branches: [main, dev, ci-*, mnt/*]
  pull_request:
    branches: [main, dev]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
          submodules: recursive
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.10
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
      - run: bun run install:workspace
      - run: bun run lint:format
      - run: bun run lint
      - run: bun run lint:circular
  test:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['20', '22', '24']
    name: Testing with bun and node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
          submodules: recursive
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.10
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: bun install
      - run: bun run build
      - run: bun run test
