name: CI

on:
  push:
    branches: [main, ci-*]
  pull_request:
    branches: [main]

jobs:
  build:
    if: github.actor != 'dependabot[bot]'
    strategy:
      matrix:
        platform: ['ubuntu-latest', 'windows-latest']
        node: ['12', '14', '16']
    runs-on: ${{ matrix.platform }}
    name: ${{ matrix.platform }} and Node ${{ matrix.node }}
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-node${{ matrix.node }}-modules-${{ hashFiles('yarn.lock') }}
      - run: npm install
      - if: ${{ matrix.platform }} == 'ubuntu-latest'
        run: npm run lint
      - if: ${{ matrix.platform }} == 'ubuntu-latest'
        run: npm run lint:format
      - run: npm run test
